// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dglxzfhuuebyvqhygpwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnbHh6Zmh1dWVieXZxaHlncHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTM2MjUsImV4cCI6MjA2ODQ4OTYyNX0.aqT_wRxiN7ycmn7SqaYCcm9Qs5BCy9bWeQoblfeLPF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});